POST http://localhost:5000/api/user/register HTTP/1.1
Content-Type: application/json

{
  "firstName":"test" ,
  "lastName":"testovich" ,
  "userName":"testest98" ,
  "email": "testovich9830@gmail.com",
  "password": "12345"
} 