GET http://localhost:5000/api/user/9/post HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhhjIjo0NTUsImlhdCI6MTYzODUyOTM0OCwiZXhwIjoxNjM4NTMyOTQ4fQ.iv7Ah5sLy1KEsQL6gW9Z_noqZu_MpqOV2f27Roc9jCM