const ACTION_TYPES = {
  GET_USER_DATA_REQUEST: "GET_USER_DATA_REQUEST",
  GET_USER_DATA_SUCCESS: "GET_USER_DATA_SUCCESS",
  GET_USER_DATA_ERROR: "GET_USER_DATA_ERROR",

  LOGOUT_USER_DATA_REQUEST: "LOGOUT_USER_DATA_REQUEST",
  LOGOUT_USER_DATA_SUCCESS: "LOGOUT_USER_DATA_SUCCESS",

  GET_POSTS_REQUEST: "GET_POSTS_REQUEST",
  GET_POSTS_SUCCESS: "GET_POSTS_SUCCESS",
  GET_POSTS_ERROR: "GET_POSTS_ERROR",

  CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_ERROR: "CREATE_POST_ERROR",

  UPDATE_POST_REQUEST: "UPDATE_POST_REQUEST",
  UPDATE_POST_SUCCESS: "UPDATE_POST_SUCCESS",
  UPDATE_POST_ERROR: "UPDATE_POST_ERROR",

  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_ERROR: "DELETE_POST_ERROR",

  SET_CURRENT_POST_REQUEST: "SET_CURRENT_POST_REQUEST",
  SET_CURRENT_POST_SUCCESS: "SET_CURRENT_POST_SUCCESS",

  REMOVE_CURRENT_POST_REQUEST: "REMOVE_CURRENT_POST_REQUEST",
  REMOVE_CURRENT_POST_SUCCESS: "REMOVE_CURRENT_POST_SUCCESS",

  SET_CONTENT_REQUEST: "SET_CONTENT_REQUEST",
  SET_CONTENT_SUCCESS: "SET_CONTENT_SUCCESS",

  CLEAR_CONTENT_REQUEST: "CLEAR_CONTENT_REQUEST",
  CLEAR_CONTENT_SUCCESS: " CLEAR_CONTENT_SUCCESS",
};

export default ACTION_TYPES;
